use_frameworks!

target 'DeclarativeLayout_Example' do
  pod 'DeclarativeLayout', :path => '../'
  pod 'Anchorage', '4.3'
  pod 'SnapKit', '4.2.0'

  target 'DeclarativeLayout_Tests' do
    inherit! :search_paths

    
  end
end
